export const data = {
    products:[
{
    id: '1',
    name: 'Pink polo Shirt',
    image: '/images/p1.jpg',
    price: '23',
    countInStock: '11',
    rating: '4.00',
    numReviews: '14',
    description: "high quality product" ,
},
{
    id: '2',
    name: 'Dark blue polo Shirt',
    image: '/images/p2.jpg',
    price: '20',
    countInStock: '16',
    rating: '4.4',
    numReviews: '15',
    description: "high quality product" ,
},
{
    id: '3',
    name: 'Blue polo Shirt',
    image: '/images/p3.jpg',
    price: '15',
    countInStock: '11',
    rating: '4.1',
    numReviews: '11',
    description: "high quality product" ,
},
{
    id: '4',
    name: 'Orange polo Shirt',
    image: '/images/p4.jpg',
    price: '19',
    countInStock: '11',
    rating: '4.5',
    numReviews: '9',
    description: "high quality product" ,
},

{
    id: '5',
    name: 'US polo Wihte Shirt',
    image: '/images/p6.jpg',
    price: '18',
    countInStock: '78',
    rating: '3.0',
    numReviews: '3.5',
    description: "Med quality product" ,
},

{
    id: '6',
    name: 'NB Sports Shoes',
    image: '/images/p5.jpg',
    price: '42',
    countInStock: '99',
    rating: '4.5',
    numReviews: '4.5',
    description: "High Quality quality product" ,
},

{
    id: '7',
    name: 'under Armour Black&White',
    image: '/images/p7.jpg',
    price: '51',
    countInStock: '45',
    rating: '4.00',
    numReviews: '4.00',
    description: "High Quality quality product" ,
},
{
    id: '8',
    name: 'under Armour Black&Red',
    image: '/images/p8.jpg',
    price: '55',
    countInStock: '33',
    rating: '5.0',
    numReviews: '5.0',
    description: "High Quality quality product" ,
},
{
    id: '9',
    name: 'under Armour Black&Red',
    image: '/images/p9.jpg',
    price: '60',
    countInStock: '22',
    rating: '4.5',
    numReviews: '4.5',
    description: "High Quality quality product" ,
},

{
    id: '10',
    name: 'Puma jacket Olive Green',
    image: '/images/p10.jpg',
    price: '39',
    countInStock: '77',
    rating: '4.0',
    numReviews: '4.5',
    description: "High Quality quality product" ,
},
{
    id: '11',
    name: 'Kurta Payjama',
    image: '/images/p11.jpg',
    price: '8',
    countInStock: '223',
    rating: '4.0',
    numReviews: '4.5',
    description: "Mid Quality quality product" ,
},
{
    id: '12',
    name: 'Hp Pavalion Laptop',
    image: '/images/p12.jpg',
    price: '225',
    countInStock: '11',
    rating: '4.5',
    numReviews: '4.5',
    description: "Mid Quality quality product" ,
},
{
    id: '13',
    name: 'Sony Headphone',
    image: '/images/p13.jpg',
    price: '29',
    countInStock: '19',
    rating: '4.5',
    numReviews: '4.5',
    description: "High Quality quality product" ,
},
{
    id: '14',
    name: '',
    image: '/images/p14.jpg',
    price: '225',
    countInStock: '11',
    rating: '4.5',
    numReviews: '4.5',
    description: "Mid Quality quality product" ,
},
{
    id: '15',
    name: 'Hp Pavalion Laptop',
    image: '/images/p12.jpg',
    price: '225',
    countInStock: '11',
    rating: '4.5',
    numReviews: '4.5',
    description: "Mid Quality quality product" ,
},
{
    id: '16',
    name: 'Hp Pavalion Laptop',
    image: '/images/p12.jpg',
    price: '225',
    countInStock: '11',
    rating: '4.5',
    numReviews: '4.5',
    description: "Mid Quality quality product" ,
},
    ]
}