export const data = {
    products:[
{
    id: '1',
    name: 'Pink polo Shirt',
    image: '/images/p1.jpg',
    price: '23',
    countInStock: '11',
    rating: '4.00',
    numReviews: '14',
    description: "high quality product" ,
},
{
    id: '2',
    name: 'Dark blue polo Shirt',
    image: '/images/p2.jpg',
    price: '20',
    countInStock: '16',
    rating: '4.4',
    numReviews: '15',
    description: "high quality product" ,
},
{
    id: '3',
    name: 'Blue polo Shirt',
    image: '/images/p3.jpg',
    price: '15',
    countInStock: '11',
    rating: '4.1',
    numReviews: '11',
    description: "high quality product" ,
},
{
    id: '4',
    name: 'Orange polo Shirt',
    image: '/images/p4.jpg',
    price: '19',
    countInStock: '11',
    rating: '4.5',
    numReviews: '9',
    description: "high quality product" ,
},

{
    id: '5',
    name: '',
    image: '/images/p6.jpg',
    price: '18',
    countInStock: '78',
    rating: '3.0',
    numReviews: '3.5',
    description: "Med quality product" ,
},
    ]
}